name: CD Pipeline Experiment 20
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker Image
        run: |
          cd experiment-16/backend
          docker build -t test-img .
      - name: Verify
        run: docker images